# SAR PDDL Problem Examples
# =====================================================================
# CRITICAL RULES FOR SAR PDDL PROBLEMS:
#   1. ALWAYS include 'base_camp' in :objects and set (at robot1 base_camp) in :init.
#      NEVER set (at robot1 <supply_src>), (at robot1 <fire_region>), or
#      (at robot1 <person>) in :init — the planner must insert GoToObject.
#   2. Include only objects referenced in the subtask.
#   3. :goal represents completion of THIS subtask only.
# =====================================================================


# EXAMPLE 1 — Subtask: Extinguish CaldorFire using Sand

(define (problem extinguish-caldorfire)
  (:domain allactionrobot)

  (:objects
    robot1 - robot
    base_camp - object
    ReservoirUtah - object
    CaldorFire_Region_1 - object
    CaldorFire_Region_2 - object
    Sand - object
    CaldorFire - object
  )

  (:init
    ; Robot starts at base camp — GoToObject will navigate it to the supply source.
    ; NEVER place (at robot1 ReservoirUtah) here.
    (at robot1 base_camp)
    (is-supply Sand)
    (has-resource ReservoirUtah Sand)
    (fire-active CaldorFire_Region_1)
    (fire-active CaldorFire_Region_2)
    (is-region CaldorFire_Region_1)
    (is-region CaldorFire_Region_2)
    (region-of CaldorFire_Region_1 CaldorFire)
    (region-of CaldorFire_Region_2 CaldorFire)
    (supply-for-fire Sand CaldorFire)
  )

  (:goal (and
    (not (fire-active CaldorFire_Region_1))
    (not (fire-active CaldorFire_Region_2))
  ))
)
; Expected plan (generated by FastDownward):
;   GoToObject(robot1, ReservoirUtah)
;   GetSupply(robot1, ReservoirUtah, Sand)
;   GoToObject(robot1, CaldorFire_Region_1)
;   UseSupply(robot1, CaldorFire_Region_1, Sand)
;   GoToObject(robot1, ReservoirUtah)
;   GetSupply(robot1, ReservoirUtah, Sand)
;   GoToObject(robot1, CaldorFire_Region_2)
;   UseSupply(robot1, CaldorFire_Region_2, Sand)


# EXAMPLE 2 — Subtask: Extinguish GreatFire using Water

(define (problem extinguish-greatfire)
  (:domain allactionrobot)

  (:objects
    robot1 - robot
    base_camp - object
    LakeHollywood - object
    GreatFire_Region_1 - object
    Water - object
    GreatFire - object
  )

  (:init
    ; Robot starts at base camp — NEVER at LakeHollywood or GreatFire_Region_1.
    (at robot1 base_camp)
    (is-supply Water)
    (has-resource LakeHollywood Water)
    (fire-active GreatFire_Region_1)
    (is-region GreatFire_Region_1)
    (region-of GreatFire_Region_1 GreatFire)
    (supply-for-fire Water GreatFire)
  )

  (:goal (and
    (not (fire-active GreatFire_Region_1))
  ))
)
; Expected plan:
;   GoToObject(robot1, LakeHollywood)
;   GetSupply(robot1, LakeHollywood, Water)
;   GoToObject(robot1, GreatFire_Region_1)
;   UseSupply(robot1, GreatFire_Region_1, Water)


# EXAMPLE 3 — Subtask: Rescue LostPersonTimmy (multi-agent)

(define (problem rescue-timmy)
  (:domain allactionrobot)

  (:objects
    robot1 - robot
    robot2 - robot
    base_camp - object
    LostPersonTimmy - object
    DepositFacility - object
  )

  (:init
    ; Both robots start at base camp — NEVER at LostPersonTimmy or DepositFacility.
    (at robot1 base_camp)
    (at robot2 base_camp)
    (is-person LostPersonTimmy)
    (person-lost LostPersonTimmy)
    (is-deposit DepositFacility)
  )

  (:goal (and
    (not (person-lost LostPersonTimmy))
  ))
)
; Expected plan (robot1 leads, robot2 supports):
;   Explore(robot1)
;   GoToObject(robot1, LostPersonTimmy)
;   Carry(robot1, LostPersonTimmy)
;   DropOff(robot1, DepositFacility, LostPersonTimmy)


# EXAMPLE 4 — Subtask: Store supplies at DepositFacility

(define (problem store-supplies)
  (:domain allactionrobot)

  (:objects
    robot1 - robot
    base_camp - object
    ReservoirUtah - object
    DepositFacility - object
    Sand - object
  )

  (:init
    ; Robot starts at base camp.
    (at robot1 base_camp)
    (is-supply Sand)
    (has-resource ReservoirUtah Sand)
    (is-deposit DepositFacility)
  )

  (:goal (and
    (stored-at DepositFacility Sand)
  ))
)
; Expected plan:
;   GoToObject(robot1, ReservoirUtah)
;   GetSupply(robot1, ReservoirUtah, Sand)
;   GoToObject(robot1, DepositFacility)
;   StoreSupply(robot1, DepositFacility)
